### ISSUE TITLE
How to dismiss viewcontroller programmatically?

### ISSUE THREAD

**Issue by londonbridges13** [SebastianBoldt/Jelly#17]
I want to remove the alert when a user taps on a button. How would I go about doing that?

**Comment by SebastianBoldt** [comment]
Just take a look at the Example Project. You can the dismiss the Viewcontroller as usual by calling the native dismiss method on it.

**Comment by londonbridges13** [comment]
I found 
`@IBAction func dismissMe(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }
`

Thanks
