### ISSUE TITLE
Help for my requirement using this beautiful library.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [SebastianBoldt/Jelly#18]
I want to show a custom designed timer control with `blurredslidein` or `fadin` effect.

The design is roughly like, Three label for Hour, Minute & Second. Two button like, Start & Cancel.

Cancel button should disappear the `viewController`. Start button starts the timer.

So, I just want to ask whether it is possible or not?

**Comment by SebastianBoldt** [comment]
Yes, sure it is possible. Just design a Viewcontroller the way you want and present it using Jelly. You can find an example on how to do this inside the Example Project.

**Comment by Rashesh-Bosamiya** [comment]
Thanks.
