### ISSUE TITLE
Centre the content of viewController in the Jelly presentation.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [SebastianBoldt/Jelly#22]
I have implemented timer design and presenting the timer using Jelly controller.

The problem is, The view is not coming up in centre.

How can I centre the content?

![simulator screen shot 11-dec-2016 12 28 31 am](https://cloud.githubusercontent.com/assets/19154948/21075472/32a15938-bf39-11e6-8b3e-2cd8c1fdfd89.png)

**Comment by SebastianBoldt** [comment]
Use Autolayout to center your Content.

**Comment by Rashesh-Bosamiya** [comment]
Okay. I made it.

**Comment by Rashesh-Bosamiya** [comment]
Thanks!

**Comment by Rashesh-Bosamiya** [comment]
One more thing,

Currently, When user touches anywhere outside the presented area, the jelly view is dismiss.

So, I want to prevent the dismiss of view when user touches outside area.

I want to dismiss view only when user click the close button.

**Comment by SebastianBoldt** [comment]
This is currently not possible but it is on the feature List of 1.1.0.
Related Issue is #14
