### ISSUE TITLE
Remove prefixes from classes etc.

### ISSUE THREAD

**Issue by SebastianBoldt** [SebastianBoldt/Jelly#27]
Prefixes are bad in Swift because there is no need for them. Please remove.

**Comment by ChristianKienle** [comment]
You can simply annotate like this:
````
NS_SWIFT_NAME(Class)
@interface XXXClass: NSObject
````
This retains the prefixes under Objective-C but gets rid of them for Swift-users.

**Comment by SebastianBoldt** [comment]
Done in 2.0.0 ✅
