### ISSUE TITLE
"isTapBackgroundToDismissEnabled" is no avaliable

### ISSUE THREAD

**Issue by mikedev-1** [SebastianBoldt/Jelly#30]
I set the property `isTapBackgroundToDismissEnabled` false, but seems to no effect
Here is my code:
`var presentation = JellySlideInPresentation(cornerRadius: 5.0,widthForViewController: .custom(value: 300),heightForViewController:.custom(value: 260))`

`presentation.directionShow = .left
presentation.directionDismiss = .right`

`presentation.isTapBackgroundToDismissEnabled = false`

`let animator = JellyAnimator(presentation: presentation)
self.jellyAnimator = animator`

`let serviceTypeViewController = ServiceTypeViewController()
self.jellyAnimator?.prepare(viewController: serviceTypeViewController)
self.present(serviceTypeViewController, animated: true, completion: nil)`

**Comment by SebastianBoldt** [comment]
Thanks for your Feedback. I will examine this Issue soon and try to keep you updated.

**Comment by SebastianBoldt** [comment]
Should be fixed in Version 1.2.1. You just need to pod update.
