### ISSUE TITLE
Presenting a ViewController over a Jelly ViewController will result in a glitch

### ISSUE THREAD

**Issue by SebastianBoldt** [SebastianBoldt/Jelly#35]
setting the modalPresentationStyle to .overFullscreen will fix the issue.
Please make the code more robust so users do not need to use .overFullscreen.

**Comment by SebastianBoldt** [comment]
![ohne titel](https://cloud.githubusercontent.com/assets/2922440/23279948/8a56831a-fa17-11e6-955f-45071f997530.gif)

**Comment by zahid119** [comment]
Any solution so far? Thanks.

**Comment by SebastianBoldt** [comment]
Hi @zahid119. The current workaround is to set the modalPresentationStyle to overFullscreen of the presented viewController. I didn't find the time to actually debug and fix this issue until today. 

```
 let modal = .... create your ViewController over here
 modal?.modalPresentationStyle = .overFullScreen
 self.present(modal!, animated: true, completion: nil)
```
