### ISSUE TITLE
Adjust height automatically with in-call status bar

### ISSUE THREAD

**Issue by vdeep** [SebastianBoldt/Jelly#39]
Is there any way we can automatically adjust the height/top of the presented view controller when in-call status bar is displayed/hidden? You can check the screenshots for reference.

![jelly-in-call-status-bar-issue](https://cloud.githubusercontent.com/assets/2727830/24398325/b5094aac-13c6-11e7-97be-3a94b3b8292c.png)

Here I've set the size of the presented view controller to be offset 20 from all sides from main screen bounds. I'm using JellySlideInPresentation with following settings:

```swift
let presentation = JellySlideInPresentation(
            dismissCurve: .easeInEaseOut,
            presentationCurve: .easeInEaseOut,
            cornerRadius: 4,
            backgroundStyle: .dimmed(alpha: 0.8),
            jellyness: .jelly,
            duration: .normal,
            directionShow: .bottom,
            directionDismiss: .bottom,
            widthForViewController: .custom(value: targetSize.width),
            heightForViewController: .custom(value: targetSize.height),
            horizontalAlignment: .center,
            verticalAlignment: .center,
            marginGuards: .zero,
            corners: .allCorners)
```

Please let me know if this is achievable.

**Comment by SebastianBoldt** [comment]
It is currently not possible to achieve this using Jelly. 
But I think it could be possible to integrate this functionality into Jellys Presentation Controller Logic. I will try to put this into the next release if its possible. 
I'll keep you up to date.  

**UPDATE**:
According to the Apple Docs this should be possible. I'll give it a try if I find some time.

![bildschirmfoto 2017-03-28 um 11 58 44](https://cloud.githubusercontent.com/assets/2922440/24399725/f7e95bfa-13ad-11e7-82b3-b683019e5cf6.png)

**Comment by SebastianBoldt** [comment]
Can be accomplished by using the new LIVE UPDATE Feature in Jelly 2.0.0.
