### ISSUE TITLE
Hide status bar for presented ViewControllers?

### ISSUE THREAD

**Issue by JohnGroenhof** [SebastianBoldt/Jelly#40]
@SebastianBoldt, Is there a way to hide the status bar for a presented ViewController, like a slide-in, for example? I've overriden prefersStatusBarHidden in the VC being presented by Jelly, but that's not doing the trick. Any help is appreciated. Thanks for the great tool!

John

**Comment by SebastianBoldt** [comment]
Hi John, sorry that I answer that late. This actually really ease to accomplish. You just need to define the logic inside the presenting viewController like so.

```
    override var prefersStatusBarHidden: Bool {
        if let viewController = self.presentedViewController {
                return viewController.prefersStatusBarHidden
        }
        return super.prefersStatusBarHidden
    }
```
