### ISSUE TITLE
Update release to support Swift 3.1 and Xcode 8.3.x

### ISSUE THREAD

**Issue by ryandailey100** [SebastianBoldt/Jelly#43]

**Comment by SebastianBoldt** [comment]
It should work with Swift 3.1 and Xcode 8.3.2, which is the latest version? 
Did you experience some  issues using Jelly and Xcode 8.3.2?

**Comment by ryandailey100** [comment]
Everything works okay, nothing that breaks my app, it's just that I get some warning messages. 
<img width="291" alt="screen shot 2017-05-26 at 1 59 43 pm" src="https://cloud.githubusercontent.com/assets/15038444/26506771/a848783c-421b-11e7-98b2-08b01b628c1e.png">

**Comment by SebastianBoldt** [comment]
Okay, I will fix that warning for you in the next jelly release. 👍

**Comment by ryandailey100** [comment]
Thanks! 👍
