### ISSUE TITLE
viewWillDisappear never called

### ISSUE THREAD

**Issue by Maryom** [SebastianBoldt/Jelly#45]
Hi,

Thanks for your repo. Before I used Jelly `viewWillDisappear` was called. Now with Jelly `viewWillDisappear` never called! Any help?

```
override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        print("Hey")
}
```

**Comment by SebastianBoldt** [comment]
This has to to with the nature of modal viewControllers in iOS. Please consult Stackoverflow for more information: https://stackoverflow.com/questions/29271880/viewdidappear-not-called-when-the-modal-view-is-dismissed

One thing you could do is to build up a delegate chain between the presenting and the presented viewController to react to the events you want.

**Comment by Maryom** [comment]
@SebastianBoldt Thank you. I solved my problem as following:

```
present(homeVC, animated: true) { _ in

            UserDefaults.standard.set(Sound.currentShaik, forKey: "currentShaik")
            
}
```
