### ISSUE TITLE
Possibility to have custom position in the screen

### ISSUE THREAD

**Issue by bidadh** [SebastianBoldt/Jelly#51]
Is it possible to have a custom position similar to the custom in size

Currently, the only way is to have .top, .bottom, .center as listed below I'm wondering if you could add custom like the following:

```swift
    public enum VerticalAlignment {
        case top
        case bottom
        case center
        case custom(y: CGFloat) 
    }

    public enum HorizontalAlignment {
        case left
        case right
        case center
        case custom(x: CGFloat) 
    }
```

I need to display the new viewController at a certain x,y

**Comment by SebastianBoldt** [comment]
Merged your Pull-Request. Should be possible in the next release.
