### ISSUE TITLE
Support preferredStatusBarStyle

### ISSUE THREAD

**Issue by NirpE** [SebastianBoldt/Jelly#62]
I can see my status bar being white instead of dark after presenting new ViewController. If I remove the Jelly related code and present it via native code it will respect the default dark style.

Is there some workaround for this?

**Comment by SebastianBoldt** [comment]
With iOS 7 custom transitions, it's possible to present a view controller that isn't fullscreen and therefore wouldn't affect the statusbar appearance. You have to explicitly tell iOS that your custom presented view controller will, in fact, control the status bar's appearance.

```
let controllerToPresent = ....
controllerToPresent.modalPresentationCapturesStatusBarAppearance = true
```
