### ISSUE TITLE
Flashing blur effect when swiping up on top of controller

### ISSUE THREAD

**Issue by glisom** [SebastianBoldt/Jelly#63]
Love the library! Literally makes life so much easier. Currently seeing a flash whenever a user swipes up from the top of the controller inside the animator when using the blur effect. Let me know what info would help, I can attach pics or a video.

**Comment by SebastianBoldt** [comment]
Hi @glisom , I am totally aware of this issue. It has to do with the animation of the blur view alongside the transitioning coordinator. I will try to inspect this later again. I already implemented a workaround some weeks ago , which animates the alpha of the blur view instead of the blur itself. But this did look weird to me. I will keep you informed about my progress in here. Stay tuned and have a nice day.

**Comment by glisom** [comment]
@SebastianBoldt awesome, glad to hear. I would like to take a stab at it if that’s cool with you. Do you have a format or anything for PR’s?

**Comment by SebastianBoldt** [comment]
There is no format or anything. Just change the things how you think it should be done and let’s talk again when the pull request is open 😋. Fyi: I am off for the next 2 days so it maybe takes some time for my next response to arrive. 

If you want to dig into the code you can take a look at the `PresentationController` class, there is a function called `animateBlurView` which will be called in `dismissalTransitionWillBegin` and `presentationTransitionWillBegin`. Setting the blur view to `nil` will actually animate correctly alongside the transitioning coordinator but there is this tiny glitch you experienced if the user lifts his finger on certain states of transition. Maybe you can find a good solution for this. 

See you later 🐊 and have a nice weekend 👋.

**Comment by SebastianBoldt** [comment]
Hi @glisom. Have you made any progress?

**Comment by glisom** [comment]
I’ve made some around getting the transition from stopping from flashing but still working on getting it to stop when the transition gets canceled
