### ISSUE TITLE
Request to put back Minimum deployment target to iOS 10

### ISSUE THREAD

**Issue by marcmatta** [SebastianBoldt/Jelly#69]
@SebastianBoldt Thank you for this great library!

Can you please explain for which reasons other than for using the maskedCorners property of the CALayer is the minimum deployment target set to iOS 11?

Although iOS 10 is not recent anymore, users are still using it and if you bring back support you will be covering close to 99% of all users.

All this requires a simple change. One similar provided by [this](https://gist.github.com/shaildyp/6cd1de39498ff7b3c22fa758f005f7cd) gist

**Comment by SebastianBoldt** [comment]
Hi @marcmatta, 
sorry for replying this late. I am currently a little busy and and in addition to that its summertime ;). This weekend the weather should be shitty so i will take a look at this and provide a new release with support for iOS 10.

**Comment by SebastianBoldt** [comment]
@marcmatta  Another reason why i chose iOS11 as a deployment target was the "name" property of the UIGestureRecognizer. I added version guards to the affected code so you will be able to use Jelly in iOS 10.

https://github.com/SebastianBoldt/Jelly/commit/65ed770c81c8e1622e817f26e97e53f9472ffadf

**Comment by SebastianBoldt** [comment]
https://github.com/SebastianBoldt/Jelly/releases/tag/2.2.1
