### ISSUE TITLE
iOS 13 glitch issue

### ISSUE THREAD

**Issue by awaisbub** [SebastianBoldt/Jelly#74]
I am presenting my ViewControllers this way by using different PresentationSize and PresentationUIConfiguration.
Presenting this way and **its creating glitches every where.**

```
let vc = UIStoryboard(name: "RideSelectionStory", bundle: nil).instantiateInitialViewController() as! RideSelectionVC
let interactionConfiguration = InteractionConfiguration(presentingViewController: self, completionThreshold: 0.5, dragMode: .edge)
let uiConfiguration = PresentationUIConfiguration(cornerRadius: 0, backgroundStyle: .dimmed(alpha: 0.92), isTapBackgroundToDismissEnabled: false)
let size = PresentationSize(width: .fullscreen, height: .custom(value: (self.view.frame.height*0.7)))
let marginGuards = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
let alignment = PresentationAlignment(vertical: .bottom, horizontal: .left)
let presentation = CoverPresentation(directionShow: .bottom, directionDismiss: .bottom, uiConfiguration: uiConfiguration, size: size, alignment: alignment, marginGuards: marginGuards, interactionConfiguration: interactionConfiguration)
let animator = Animator(presentation: presentation)
self.animator = animator
animator.prepare(presentedViewController: vc)
self.present(vc,animated: true)
```

**and it is giving a glitch on iOS 13. What can be the solution for this issue?**

**Comment by SebastianBoldt** [comment]
Which version of Jelly are you using?

**Comment by awaisbub** [comment]
I am using 2.0 version. It was working fine in all of my projetcs. but as I checked it on iOS 13, there was a weird glitch only on dismiss viewcontroller.
viewcontroller dismiss with a glitch.
and it happened in all of projects in which I used this pod.

**Comment by SebastianBoldt** [comment]
I am pushing the latest version to the trunk tomorrow (2.2.2). Try to use the master for so long, it should fix your problems.

**Comment by SebastianBoldt** [comment]
Try to upgrade to the latest version 2.2.2.
